import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import { requireUserId } from "./auth";
import { calculateWeightedScore } from "./scoring";

const entityType = v.union(v.literal("company"), v.literal("opportunity"));

async function calculateOverall(ctx: any, user: string, type: "company" | "opportunity", entityId: string) {
  const criteria = (await ctx.db.query("ratingCriteria").withIndex("by_user", (q: any) => q.eq("workosUserId", user)).collect()).filter((item: any) => item.entityType === type);
  const values = await ctx.db.query("ratingValues").withIndex("by_entity", (q: any) => q.eq("workosUserId", user).eq("entityType", type).eq("entityId", entityId)).collect();
  const scores = new Map<string, number>(values.map((item: any) => [String(item.criterionId), Number(item.score)]));
  const overall = calculateWeightedScore(criteria.map((item: any)=>({id:String(item._id),maxScore:item.maxScore,weight:item.weight})),scores);
  const id = ctx.db.normalizeId(type === "company" ? "companies" : "opportunities", entityId);
  if (id) await ctx.db.patch(id, { overallScore: overall, updatedAt: Date.now() });
  return overall;
}

export const listCriteria = query({ args: { workosUserId: v.string() }, handler: async (ctx, args) => { await requireUserId(ctx, args.workosUserId); return ctx.db.query("ratingCriteria").withIndex("by_user", q => q.eq("workosUserId", args.workosUserId)).collect(); } });
export const listValues = query({ args: { workosUserId: v.string(), entityType, entityId: v.string() }, handler: async (ctx, args) => { await requireUserId(ctx, args.workosUserId); return ctx.db.query("ratingValues").withIndex("by_entity", q => q.eq("workosUserId", args.workosUserId).eq("entityType", args.entityType).eq("entityId", args.entityId)).collect(); } });
export const listAllValues = query({ args: { workosUserId: v.string() }, handler: async (ctx, args) => { await requireUserId(ctx, args.workosUserId); return ctx.db.query("ratingValues").withIndex("by_user", q => q.eq("workosUserId", args.workosUserId)).collect(); } });

export const createCriterion = mutation({ args: { workosUserId: v.string(), name: v.string(), description: v.optional(v.string()), entityType, maxScore: v.number(), weight: v.number() }, handler: async (ctx, args) => { await requireUserId(ctx, args.workosUserId); const rows = await ctx.db.query("ratingCriteria").withIndex("by_user", q => q.eq("workosUserId", args.workosUserId)).collect(); const name = args.name.trim(); if (!name) throw new Error("Criterion name is required"); return ctx.db.insert("ratingCriteria", { ...args, name, maxScore: Math.max(1, args.maxScore), weight: Math.max(0, args.weight), order: rows.filter(row => row.entityType === args.entityType).length }); } });
export const updateCriterion = mutation({ args: { workosUserId: v.string(), criterionId: v.id("ratingCriteria"), name: v.optional(v.string()), description: v.optional(v.string()), maxScore: v.optional(v.number()), weight: v.optional(v.number()), order: v.optional(v.number()) }, handler: async (ctx, args) => { await requireUserId(ctx, args.workosUserId); const row = await ctx.db.get(args.criterionId); if (!row || row.workosUserId !== args.workosUserId) throw new Error("Rating criterion not found"); const { criterionId, workosUserId, ...patch } = args; await ctx.db.patch(criterionId, { ...patch, ...(patch.name ? { name: patch.name.trim() } : {}), ...(patch.maxScore !== undefined ? { maxScore: Math.max(1, patch.maxScore) } : {}), ...(patch.weight !== undefined ? { weight: Math.max(0, patch.weight) } : {}) }); const values = await ctx.db.query("ratingValues").withIndex("by_user", q => q.eq("workosUserId", args.workosUserId)).collect(); const entityIds = [...new Set(values.filter(value => value.entityType === row.entityType).map(value => value.entityId))]; for (const entityId of entityIds) await calculateOverall(ctx, args.workosUserId, row.entityType, entityId); } });
export const removeCriterion = mutation({ args: { workosUserId: v.string(), criterionId: v.id("ratingCriteria") }, handler: async (ctx, args) => { await requireUserId(ctx, args.workosUserId); const row = await ctx.db.get(args.criterionId); if (!row || row.workosUserId !== args.workosUserId) throw new Error("Rating criterion not found"); const values = await ctx.db.query("ratingValues").withIndex("by_user", q => q.eq("workosUserId", args.workosUserId)).collect(); const affected = [...new Set(values.filter(value => value.criterionId === args.criterionId).map(value => value.entityId))]; for (const value of values.filter(value => value.criterionId === args.criterionId)) await ctx.db.delete(value._id); await ctx.db.delete(args.criterionId); for (const entityId of affected) await calculateOverall(ctx, args.workosUserId, row.entityType, entityId); } });
export const setValue = mutation({ args: { workosUserId: v.string(), criterionId: v.id("ratingCriteria"), entityType, entityId: v.string(), score: v.number() }, handler: async (ctx, args) => { await requireUserId(ctx, args.workosUserId); const criterion = await ctx.db.get(args.criterionId); if (!criterion || criterion.workosUserId !== args.workosUserId || criterion.entityType !== args.entityType) throw new Error("Rating criterion not found"); const entity = await ctx.db.get(args.entityId as any); if (!entity || entity.workosUserId !== args.workosUserId) throw new Error("Rated record not found"); const values = await ctx.db.query("ratingValues").withIndex("by_entity", q => q.eq("workosUserId", args.workosUserId).eq("entityType", args.entityType).eq("entityId", args.entityId)).collect(); const match = values.find(value => value.criterionId === args.criterionId); const score = Math.max(0, Math.min(criterion.maxScore, args.score)); if (match) await ctx.db.patch(match._id, { score, updatedAt: Date.now() }); else await ctx.db.insert("ratingValues", { workosUserId: args.workosUserId, criterionId: args.criterionId, entityType: args.entityType, entityId: args.entityId, score, updatedAt: Date.now() }); return calculateOverall(ctx, args.workosUserId, args.entityType, args.entityId); } });
