import { useMutation, useQuery } from "convex/react";
import { BarChart3, Building2, Plus, Scale, Trash2 } from "lucide-react";
import { useState, type FormEvent } from "react";
import { api } from "../../../convex/_generated/api";

export function RatingConfiguration({ workosUserId }: { workosUserId?: string }) {
  const criteria = useQuery(api.ratings.listCriteria, workosUserId ? { workosUserId } : "skip");
  const create = useMutation(api.ratings.createCriterion); const remove = useMutation(api.ratings.removeCriterion);
  const [entityType, setEntityType] = useState<"company"|"opportunity">("company");
  const relevant = (criteria ?? []).filter(item => item.entityType === entityType).sort((a,b)=>a.order-b.order);
  const totalWeight = relevant.reduce((sum,item)=>sum+item.weight,0);
  if (!workosUserId) return null;
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);const name=String(data.get("name")??"").trim();if(!name)return;void create({workosUserId,name,description:String(data.get("description")??"").trim()||undefined,entityType,maxScore:Number(data.get("maxScore")||100),weight:Number(data.get("weight")||10)}).then(()=>form.reset());};
  return <section className="rating-settings"><div className="settings-section-heading"><div><h2>Weighted ratings</h2><p>Build a scorecard once; Waypoint normalises weights and ranks records automatically.</p></div><span className={totalWeight===100?"weight-ok":""}><Scale size={13}/>{totalWeight}% allocated</span></div><div className="rating-tabs"><button className={entityType==="company"?"active":""} onClick={()=>setEntityType("company")}><Building2 size={13}/> Companies</button><button className={entityType==="opportunity"?"active":""} onClick={()=>setEntityType("opportunity")}><BarChart3 size={13}/> Opportunities</button></div><div className="criteria-board"><div className="criteria-list">{relevant.length ? relevant.map((item,index)=><div className="criterion-row" key={item._id}><span className="criterion-order">{String(index+1).padStart(2,"0")}</span><div><strong>{item.name}</strong><small>{item.description||`Scored from 0–${item.maxScore}`}</small></div><span className="criterion-weight">{item.weight}%</span><button aria-label={`Delete ${item.name}`} onClick={()=>void remove({workosUserId,criterionId:item._id})}><Trash2 size={13}/></button></div>) : <div className="criterion-empty"><Scale size={19}/><strong>No criteria yet</strong><span>Add the signals that matter to your decision.</span></div>}</div><form className="criterion-form" onSubmit={submit}><div><p className="page-kicker">New criterion</p><h3>Add to scorecard</h3></div><label><span>Name</span><input name="name" required placeholder="Career prospects"/></label><label><span>Description <small>optional</small></span><input name="description" placeholder="Long-term progression and pathways"/></label><div className="criterion-number-grid"><label><span>Maximum</span><input name="maxScore" type="number" min="1" defaultValue="100"/></label><label><span>Weight</span><span className="number-suffix"><input name="weight" type="number" min="0" max="100" defaultValue="10"/><i>%</i></span></label></div><button type="submit"><Plus size={14}/> Add criterion</button></form></div></section>;
}
