import * as Dialog from "@radix-ui/react-dialog";
import { useAuth } from "@workos-inc/authkit-react";
import { useMutation, useQuery } from "convex/react";
import { Building2, ChevronRight, ExternalLink, Linkedin, Plus, Search, Trash2, Users, X } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { api } from "../../../convex/_generated/api";
import type { Id } from "../../../convex/_generated/dataModel";
import { Button } from "@/components/ui/button";

type Contact = any;

export function ContactWorkspace() {
  const { user } = useAuth(); const uid = user?.id;
  const contacts = useQuery(api.contacts.list, uid ? { workosUserId: uid } : "skip");
  const companies = useQuery(api.companies.list, uid ? { workosUserId: uid } : "skip");
  const create = useMutation(api.contacts.create); const update = useMutation(api.contacts.update); const remove = useMutation(api.contacts.remove);
  const [search, setSearch] = useState(""); const [addOpen, setAddOpen] = useState(false); const [selectedId, setSelectedId] = useState<Id<"contacts"> | null>(null);
  const selected = (contacts ?? []).find(contact => contact._id === selectedId) ?? null;
  const rows = useMemo(() => (contacts ?? []).filter((item: Contact) => `${item.name} ${item.role ?? ""} ${item.company?.name ?? ""}`.toLowerCase().includes(search.toLowerCase())), [contacts, search]);
  return <div className="data-page contact-workspace">
    <header className="page-command"><div><h1>Contacts</h1></div><Button onClick={() => setAddOpen(true)}><Plus size={15}/> Add contact</Button></header>
    <section className="metric-ribbon contact-metrics"><div><span>People</span><strong>{contacts?.length ?? 0}</strong></div><div><span>Companies covered</span><strong>{new Set((contacts ?? []).map((item: Contact) => item.companyId)).size}</strong></div><div><span>LinkedIn profiles</span><strong>{contacts?.filter((item: Contact) => item.linkedinUrl).length ?? 0}</strong></div><div className="ribbon-note"><Users size={16}/><span>A deliberately lightweight network.</span></div></section>
    <section className="records-shell"><div className="table-toolbar"><label className="table-search"><Search size={15}/><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search people, roles, companies…"/>{search && <button onClick={() => setSearch("")}><X size={13}/></button>}</label><span className="contact-count-label">{rows.length} {rows.length === 1 ? "contact" : "contacts"}</span></div>
      {contacts === undefined ? <div className="table-skeleton">{Array.from({length:5}).map((_,index)=><div key={index}><i/><span/><b/><em/></div>)}</div> : rows.length === 0 ? <div className="company-empty"><div className="empty-mark"><Users size={22}/><span><Plus size={12}/></span></div><h2>{search ? "No matching contacts" : "Your network starts here"}</h2><p>{search ? "Try a broader name, role, or company." : "Keep the useful context close without turning Waypoint into a CRM."}</p>{!search && <Button onClick={()=>setAddOpen(true)}><Plus size={14}/> Add your first contact</Button>}</div> : <div className="contact-list"><div className="contact-list-head"><span>Person</span><span>Company</span><span>LinkedIn</span><span/></div>{rows.map((item: Contact)=><button key={item._id} className="contact-row" onClick={()=>setSelectedId(item._id)}><span className="contact-person"><i>{initials(item.name)}</i><b>{item.name}<small>{item.role || "Role not added"}</small></b></span><span className="contact-company"><Building2 size={13}/>{item.company?.name}</span><span>{item.linkedinUrl ? <em className="linked-pill"><Linkedin size={12}/> Connected</em> : <em className="muted-pill">Not added</em>}</span><ChevronRight size={14}/></button>)}</div>}
    </section>
    <ContactForm open={addOpen} onOpenChange={setAddOpen} companies={companies ?? []} onSubmit={async (values: {companyId: Id<"companies">; name: string; role?: string; linkedinUrl?: string}) => { if(!uid) return; await create({workosUserId:uid,...values}); setAddOpen(false); }}/>
    <ContactSheet contact={selected} companies={companies ?? []} open={!!selected} onOpenChange={(value: boolean)=>!value&&setSelectedId(null)} onSave={async (patch: {companyId?: Id<"companies">; name?: string; role?: string; linkedinUrl?: string; notes?: string})=>{if(uid&&selected) await update({workosUserId:uid,contactId:selected._id,...patch});}} onDelete={async()=>{if(uid&&selected){await remove({workosUserId:uid,contactId:selected._id});setSelectedId(null);}}}/>
  </div>;
}

function ContactForm({open,onOpenChange,companies,onSubmit}:any){const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const linkedinUrl=String(data.get("linkedinUrl")??"").trim();onSubmit({companyId:data.get("companyId") as Id<"companies">,name:String(data.get("name")).trim(),role:String(data.get("role")??"").trim()||undefined,linkedinUrl:linkedinUrl||undefined});};return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="record-dialog"><div className="dialog-title-row"><div><p className="page-kicker">New person</p><Dialog.Title>Add contact</Dialog.Title><Dialog.Description>Save only the context you will actually use.</Dialog.Description></div><Dialog.Close><X size={17}/></Dialog.Close></div><form onSubmit={submit} className="stacked-form"><label><span>Name</span><input name="name" placeholder="Alex Morgan" required autoFocus/></label><label><span>Company</span><select name="companyId" required defaultValue=""><option value="" disabled>Select company</option>{companies.map((company:any)=><option value={company._id} key={company._id}>{company.name}</option>)}</select></label><label><span>Role <small>optional</small></span><input name="role" placeholder="Early careers recruiter"/></label><label><span>LinkedIn <small>optional</small></span><input name="linkedinUrl" type="url" placeholder="https://linkedin.com/in/…"/></label><div className="dialog-actions"><Dialog.Close asChild><Button type="button" variant="ghost">Cancel</Button></Dialog.Close><Button type="submit"><Plus size={14}/> Add contact</Button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root>}

function ContactSheet({contact,companies,open,onOpenChange,onSave,onDelete}:any){if(!contact)return null;return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="company-sheet contact-sheet" onOpenAutoFocus={event=>event.preventDefault()}><Dialog.Title className="sr-only">{contact.name}</Dialog.Title><Dialog.Description className="sr-only">Contact details</Dialog.Description><div className="contact-sheet-hero"><span className="contact-hero-avatar">{initials(contact.name)}</span><div><p className="page-kicker">Contact record</p><h2>{contact.name}</h2><span>{contact.role||"Role not added"} · {contact.company?.name}</span></div><Dialog.Close className="sheet-close"><X size={18}/></Dialog.Close></div><div className="sheet-body"><section className="sheet-section"><header><h2>Profile</h2></header><label className="contact-edit-field"><span>Name</span><input defaultValue={contact.name} onBlur={event=>event.target.value.trim()&&event.target.value!==contact.name&&onSave({name:event.target.value.trim()})}/></label><label className="contact-edit-field"><span>Company</span><select value={contact.companyId} onChange={event=>onSave({companyId:event.target.value})}>{companies.map((company:any)=><option value={company._id} key={company._id}>{company.name}</option>)}</select></label><label className="contact-edit-field"><span>Role</span><input defaultValue={contact.role??""} placeholder="Add a role" onBlur={event=>event.target.value!==contact.role&&onSave({role:event.target.value})}/></label><label className="contact-edit-field"><span>LinkedIn</span><input defaultValue={contact.linkedinUrl??""} placeholder="Add LinkedIn URL" onBlur={event=>event.target.value!==contact.linkedinUrl&&onSave({linkedinUrl:event.target.value})}/></label>{contact.linkedinUrl&&<a className="linkedin-action" href={contact.linkedinUrl} target="_blank" rel="noreferrer"><Linkedin size={14}/> Open LinkedIn profile <ExternalLink size={12}/></a>}</section><section className="sheet-section"><header><h2>Notes</h2></header><textarea defaultValue={contact.notes??""} placeholder="Conversation context, how you met, useful details…" onBlur={event=>event.target.value!==contact.notes&&onSave({notes:event.target.value})}/></section><button className="danger-link" onClick={onDelete}><Trash2 size={13}/> Move contact to trash</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>}

function initials(name:string){return name.split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase()}
